apiVersion: v1
kind: Service
metadata:
  name: ca-insurance
  labels:
    app: ca-insurance
spec:
  type: ClusterIP
  selector:
    app: ca-insurance
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054