apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-insurance
spec:
  selector:
    matchLabels:
      app: ca-insurance
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-insurance
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:

        - name: ca-insurance
          image: hyperledger/fabric-ca:1.4.9
          imagePullPolicy: "Always"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw","--port","8054", "-d"
            ]
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          env:
           - name: FABRIC_CA_SERVER_CA_NAME
             value: ca-insurance
           - name: FABRIC_CA_SERVER_TLS_ENABLED
             value: "true"
           - name: FABRIC_CA_SERVER_CSR_CN
             value: "ca-insurance"
           - name: FABRIC_CA_SERVER_CSR_HOSTS
             value: "ca-insurance"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/insurance