apiVersion: v1
kind: Service
metadata:
  name: ca-officer
  
  labels:
    app: ca-officer
spec:
  type: ClusterIP
  selector:
    app: ca-officer
  ports:
    - protocol: TCP
      targetPort: 6054
      port: 6054