apiVersion: v1
kind: Service
metadata:
  name: ca-researchers
  
  labels:
    app: ca-researchers
spec:
  type: ClusterIP
  selector:
    app: ca-researchers
  ports:
    - protocol: TCP
      targetPort: 10054
      port: 10054